label escena_2_RM:
    scene fondoNegro
    narrador"Al otro día…"
    with fade
    scene casa
    emir"¡¡Rayos!! Voy a llegar tarde."
    narrador"Emir mira el lugar y se da cuenta de que está en su casa, la cual está es un completo desorden."
    emir"Verdad, estaba soñando hasta hace un momento."
    emir"Cada vez los sueños se ponen peores."
    emir"Parece que tendré que hacer algo… pero ¿Que hago?"
    narrador"Emir mira la hora y se da cuenta de que va a llegar tarde a la escuela si no se apresura."
    emir"Como sea, no tengo tiempo ahora, se me ocurrirá algo en otro momento."
    narrador"Casi con un esfuerzo demencial, Emir logra llegar justo a tiempo a la escuela."
    emir"¡affffff! maldición… uffffff!!!!"
    narrador"Aún exaltado y con la cara sudorosa, Emir se apresura para tomar su asiento en el salón de clases."
    emir"Por fin…fiuuuu ufffff llegue. Casi no lo consigo."
    narrador"Las clases pasan sin mucha complicación. Al terminar de recoger sus cosas de su escritorio, Emir toma su ruta habitual a la biblioteca."
    emir"Mmmm, parece que Albedo no ha llegado, que raro."
    narrador"Mientras que Albedo llegaba, Emir estaba pensando en qué hacer con su problema del sueño, pero estaba tan ensimismado que no se dio cuenta de que Albedo ya había llegado hace un rato."
    albedo"Emir… ¿Emir? Tierra llamando a Emir."
    emir"¿Qué? ¿Cuándo llegaste Albedo?"
    albedo"Hace un rato… te he estado llamando desde que llegué."
    albedo"¿Todo está bien? Pareces más distraído que de costumbre."
    albedo"Y tienes ojeras, ¿Estás durmiendo bien? Por lo menos deberías dormir 6 horas diarias."
    emir"Yo no estoy distraído y estoy completamente bien."
    albedo"Si si, lo que digas."
    narrador"Después de esto, la conversación se detiene e inmediatamente Emir se vuelve a perder en sus pensamientos."
    albedo"Bueno aprovechando el hecho de que estás tan atento… ¿Quieres ir un rato al centro comercial el proximo dia libre?"
    emir"Ah… si si."
    albedo"Jajajaja nunca pensé que sería tan fácil."
    emir"¿De que te estas riendo?"
    albedo"De nada importante, entonces nos vemos en el centro comercial a las 3 de la tarde, ¿Qué te parece?"
    emir"¡¿Qué?! ¿De qué estás hablando?"
    emir"¿Como que centro comercial?, yo nunca dije que iría…"
    albedo"Si lo hiciste, justo después de decir que no estabas distraído."
    emir"Pero eso no vale, no tiene sentido."
    albedo"Si vale, claro que vale."
    albedo"Bueno tomaré esa respuesta como un “Estoy de acuerdo con ir al centro comercial a las 3 de la tarde” o algo así."
    albedo"Tengo otras cosas que hacer, así que me iré, nos vemos el domingo en el centro comercial, no llegues tarde."
    emir"¿Qué? no espera, cómo te vas a ir si ni siquiera hemos acabado el turno en la biblioteca…"
    albedo"..."
    emir"¿Es enserio?"
    albedo"..."
    emir"Y se fue…"
    emir"Enserio, se fue antes de tiempo y ahora tengo que acompañarlo a ir al centro comercial por estar distraído."
    emir"Pero no estoy seguro de hacerlo..."
    emir"Ahora la pregunta es: ¿Ser o no ser?"
    emir"Ahhhh ya estoy enloqueciendo"
    emir"No se porque me estoy contandome chistes a mi mismo..."
    emir"Como sea, ¿Si acompaño a Albedo a ir al centro comercial?"

    jump decicion1