label escena_3_RM:
    narrador"Es el día del encuentro. Emir, llega antes de la hora prevista para reunirse con Albedo."
    emir"Estoy tan nervioso, no he salido con nadie desde que vivo en esta ciudad y termine llegando 20 minutos antes."
    emir"Como era de esperarse, Albedo no ha llegado aún."
    narrador"10 minutos después llega Albedo."
    albedo"¡Hey! ¡Emir!"
    albedo"Parece que también querías venir, porque llegaste antes que yo."
    emir"No te hagas ideas extrañas, es solo que salí antes de casa porque tenía que hacer otras cosas antes de encontrarme contigo."
    emir"No es como que llegara antes por equivocación."
    albedo"Dudo mucho que salieras de casa si alguien no te obliga, ya que no es un secreto que no sales de casa casi que por ninguna razón."
    albedo"Por cierto, como dato que nunca preguntaste, la vitamina D se obtiene de la luz solar y esa es una vitamina muy beneficiosa para los huesos."
    emir"¿Sabes? Deberías dejar esa costumbre de decir cosas totalmente aleatorias."
    albedo"jajajaja. Lo siento."
    albedo"Como sea, ¿Sabes para que te pedí que vinieras?"
    emir"¿Para que te acompañe a hacer algo?"
    albedo"¡Correcto! Más concretamente a la sala de videojuegos, he querido jugar con alguien pero no he podido, porque no tengo amigos que les guste."
    emir"Bueno ciertamente no pareces el tipo de persona que le gusten los videojuegos."
    albedo"Aunque no lo parezca, tengo un gran interés por los videojuegos."
    emir"Nunca dejas de sorprenderme."
    albedo"Bueno, ¿Vamos ya?"
    emir"Está bien, vamos."
    emir"¿Qué se supone que vamos a jugar?"
    albedo"No seas impaciente, ya lo veras, de seguro te va a gustar."
    narrador"Emir y Albedo juego juntos hasta que se cansan y deciden ir a otro lugar a comer algo."
    albedo"Me divertí bastante jugando contigo, fue agradable."
    emir"Es verdad, yo también la pase bien."
    albedo"Aunque tengo algo de hambre, ¿Vamos a comer en alguna cafetería cercana?"
    emir"Bueno, también me está empezando a dar algo de hambre."
    albedo"Esta cafetería es buena, ¿Qué dices? ¿Comemos acá?"
    emir"La verdad no sé mucho sobre cafeterías, así que por mí está bien."
    albedo"Entonces está decidido, comeremos aquí."
    narrador"Emir y Albedo piden lo que van a comer y mientras que esperan a que llegue su pedido hablan de algunas cosas importantes."
    albedo"Sabes Emir, la comida que pedimos no es difícil de preparar."
    emir"¿Porque hablas como si supieras preparar la comida que pedimos?"
    albedo"Eso es porque, en efecto, se como hacerlo."
    albedo"Es bastante sencillo y no toma mucho tiempo que digamos."
    albedo"Si aprendieras a cocinar, no solo tu salud mejorará, sino también tu estado de ánimo, no tienes que ser un genio como para darte cuenta de que si comes algo que te gusta, te sentirás feliz."
    emir"Bueno tienes razón."
    emir"Por cierto, ¿cómo aprendiste a cocinar?"
    albedo"Una vieja amiga me enseñó."
    emir"Pero yo no tengo quien me enseñe."
    albedo"Diría que yo te ayudaría, pero no tengo casi tiempo, ya que estoy bastante ocupado con cosas personales, prácticamente hoy fue el último día que pude salir a divertirme."
    emir"Bueno no pasa nada, igualmente gracias por el consejo."
    "¡¿Albedo?!"
    "¡Vaya, eres tú! Tiempo sin verte."
    albedo"¿Eh? Amelia, ¡Qué sorpresa verte por aquí!"
    albedo"¿Cómo has estado?"
    amelia"Muy bien ¿Y tú?"
    albedo"Bien."
    albedo"De todas las personas, no pensé encontrarme contigo jajajajaja."
    amelia"Tienes razón, ¿tal vez sea el destino? jajajajaja."
    albedo"¡Oh cierto! Emir, ella es Amelia. Es una amiga de la infancia. De hecho ella es quien me enseño a cocinar."
    amelia"Mucho gusto Emir."
    emir"M… Mu… Mucho gusto Amelia."
    albedo"Jajajajajaja no tienes porque ponerte nervioso Emir, Amelia es muy amigable al igual que yo."
    emir"Si como no, y quien dijo que estaba nervioso…"
    amelia"Jajajajaja, son un par muy divertido ¿Saben?"
    amelia"Emir me recuerda a como eras antes Albedo."
    albedo"Si es cierto, aunque esa historia será para otro momento."
    albedo"Quien sabe, tal vez por eso me llevo tan bien con Emir."
    narrador"Luego de las presentaciones por ambas partes. Albedo invita a Amelia a tomar asiento."
    narrador"Amelia se sienta junto a Albedo. De inmediato, los tres comienzan a tener una serie de conversaciones tribales."
    narrador"De forma ocasional, Amelia suelta pequeños fragmentos de su pasado con Albedo, haciendo que Emir entienda de una forma muy general su personalidad."
    emir"Vaya… Amelia realmente es una persona interesante."
    albedo"¿Ah?"
    amelia"¿Ah?"
    narrador"Sin percatarse de que lo había dicho en voz alta. Generando un silencio incómodo."
    albedo"jajajajajajajaja. Interesante, ¿Ehhh? Tienes razón, no todos los días encuentra a una biblio maniática como ella."
    amelia"¡No lo soy! No me hagas ver como una persona que solo lee todo el día."
    albedo"Pero… ¿Eso no es lo que haces todos los días?"
    amelia"¡¡¡Ahh!!!. Es cierto jajajajajajaja."
    albedo"Jajajajajaja."
    emir"Jajajajajajaja."
    narrador"Los tres continúan charlando durante un tiempo. De repente, el teléfono de Amelia suena y procede a revisarlo."
    amelia"¿Ah? pero ¡Qué tarde es! yo solo iba a saludar y ya ha pasado casi una hora. Lo siento, pero tengo que ir."
    amelia"Albedo fue un gusto verte después de tanto tiempo y Emir, tu también eres una persona interesante jejeje. Nos vemos."
    albedo"Chao."
    emir"Adiós."
    narrador"Amelia se marcha del lugar con prisa. Dejando a Emir y Albedo solos."
    narrador"Albedo se voltea a donde está Emir y lo mira con una cara de burla."
    albedo"Entonces…"
    emir"¿Entonces?"
    albedo"¿Qué te parece?"
    emir"¿Qué?"
    albedo"Vamos, no tienes que ocultarlo, dime: ¿Qué te ha parecido Amelia?. Por lo menos responde algo mejor que un simple “Interesante”."
    emir"Bueno… Es la primera vez que conozco a alguien que sea tan apasionada por la lectura, lo único que solo escuchaba de ella eran todos los libros que había leído y estaba leyendo."
    emir"No sabía que la lectura fuera un mundo tan interesante, hasta me dieron ganas de leer ese libro que no paraba de mencionar. ¿Cuál era su nombre?"
    albedo"Ahhh si, se de cual estas hablando, ese libro se llama “Alicia a través del espejo”. Este es la secuela directa del mítico cuento para niños: “Alicia en el país de las maravillas."
    albedo"Aunque recomiendo que leas primero la precuela. Creeme, su autor Lewis Carroll, es una persona con una bibliografía bastante interesante. Aunque no soy un experto en el tema."
    albedo"Si quieres saber más sobre el mundo de la lectura y sobre este autor, deberías pedirle a Amelia que te ayude con esto."
    emir"Oh, no. Albedo entró en modo Sabio de las montañas."
    narrador"Albedo continúa hablando, ignorando a Emir."
    albedo"Recuerda, la lectura tiene muchos beneficios, como el ayudar a retener más información o tener un mejor nivel de concentración y hasta de expresión."
    albedo"Pero bueno… Volviendo al tema principal."
    albedo"Parece que has tenido una buena impresión de Amelia."
    emir"Si, eso creo."
    albedo"Aunque la lectura no es todo lo que conforma su personalidad. También es buena cocinando, tiene buenas calificaciones… y tiene sobre todo un estupido potencial para la escritura…"
    narrador"Terminando con la última frase en voz baja."
    emir"Eh? ¿Qué fue lo último que dijiste?"
    albedo"No es nada. Solo ignoralo."
    emir"Ok…"
    narrador"Albedo se detiene un momento y mira fijamente a Emir."
    albedo"Dime… Emir."
    emir"¿Qué pasa? ¿Por qué te ves tan serio?"
    albedo"No fue una casualidad que te haya invitado aquí. La verdad es que desde hace un tiempo te he estado observando y hay algo que me está preocupando."
    emir"¿De qué estás hablando?"
    albedo"Emir, no estás durmiendo lo suficiente verdad. De hecho, apostaría a que ni siquiera te estás alimentando como es debido. Además, siempre tienes una mirada perdida, como si algo te preocupara constantemente."
    emir"No se a que te refieres! Estoy…. perfectamente bien. ¡¿Esta reunión solo era para acusarme?!"
    narrador"Albedo se sorprende con la expresión de exaltación de Emir. Toma una larga bocanada de aire y suelta un suspiro. Haciendo que su cara se vea más relajada."
    albedo"Está bien…"
    albedo"No tienes porque exaltarte."
    albedo"Creeme, no quería ofenderte ni nada…Es solo que como amigo realmente estoy preocupado por ti…"
    albedo"Por eso… te lo imploro!"
    narrador"Albedo de forma brusca hace una seña de disculpa y súplica."
    emir"Que… ¿Qué es lo que quieres?"
    albedo"¡Por favor Emir, déjame ayudarte!"
    emir"¿Por qué estás tan empeñado en ayudarme?"
    emir"Para ti solo soy un amigo más del montón. Solo soy la opción D, el relleno del grupo, la persona que solo se usa como última alternativa."
    albedo"¡¡Eso no es cierto!!"
    albedo"Puede que te parezca eso, pero no es verdad. Emir para mi realmente eres un gran amigo irremplazable."
    emir"Eso… es mentira."
    narrador"Emir baja la mirada y le habla a Albedo sin mirarlo."
    emir"Todo lo que dices es mentira…Lo único que quieres es burlarte de mi…"
    narrador"La voz de Albedo cambia a una más melancólica y pasiva."
    albedo"¿Sabes? No siempre he tenido este tipo de personalidad. Antes veía mi vida como un sin sentido, pasaba todo el día en el centro de Videojuegos o simplemente en mi casa."
    albedo"Los estudios, los amigos, la familia, yo mismo. Nada de eso me importaba…. Solo vivía el día a día esperando que por alguna clase de cruel destino, mi vida terminara."
    albedo"De hecho…"
    albedo"En esa epoca, intente suicidarme en una ocasion."
    narrador"Al terminar de escuchar esto, Emir rápidamente mira la expresión de Albedo, que ahora estaba llena de pena y amargura."
    emir"..."
    albedo"Veras… Solo con investigar un poco en internet me di cuenta que puedes acabar con tu vida con un gran número de pastillas de diferentes tipos… Por eso, busqué todos los medicamentos más fuertes que había en mi casa y los tomé de golpe."
    albedo"Pero…para mi mala o buena suerte, solo termine intoxicado. Simplemente me llevaron al hospital. Ni mis padres, ni amigos supieron nunca de eso… ni siquiera Amelia sabe sobre esto…"
    albedo"Eres el primero al que se lo cuento…"
    emir"¿Qué acaba de decir?"
    narrador"Emir no creía lo que estaba escuchando. ¿Cómo era posible que el amigo que siempre sonreía, pudiera tan siquiera estar triste o mucho menos, intentar quitarse la vida?"
    albedo"Emir… Ahora mismo me recuerdas a mi yo del pasado, es por eso…"
    albedo"Es por eso… que quiero ayudarte! ¡Por favor Emir!"
    albedo"Se que puede sonar egoísta y hasta terco, pero dejame ayudarte. Ya no quiero ver como mi mejor amigo se sigue autodestruyendo."
    albedo"Por favor… ¡Emir!"
    narrador"Terminando la frase con su voz casi rota como si fuese a llorar."
    emir"Albedo… yo…"
    albedo"Si me dejas ayudarte, no te prometo que toda tu vida sea perfecta, pero por lo menos estarás mucho mejor de como estás ahora."
    narrador"Emir que solo puedo escuchar toda la historia de Albedo, no sabia que hacer. Estaba estupefacto en su asiento."
    albedo"Tengo un plan que me ayudó en el pasado y que se que te puede ayudar."

    jump decicion2